obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
map_topic: /merged_map
subscribe_to_updates: true
global_frame: merged_map
always_send_full_costmap: true
