# robot_base_frame: base_link
robot_base_frame: rosbot2/base_link
costmap_topic: /merged_map
costmap_updates_topic: /merged_map_updates
visualize: true
track_unknown_space: true
planner_frequency: 0.33
progress_timeout: 30.0
potential_scale: 3.0
orientation_scale: 0.0
gain_scale: 1.0
transform_tolerance: 0.3
min_frontier_size: 0.75
# min_frontier_size: 0.1
