TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_vel_theta: 0.35
  min_vel_theta: -0.35
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 0.2
  acc_lim_x: 1.5
  acc_lim_Y: 1.5

  holonomic_robot: false
  meter_scoring: true
  pdist_scale: 5.0
  gdist_scale: 2.5

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25